FROM resin/rpi-raspbian:wheezy
MAINTAINER Peter Rossbach <peter.rossbach@bee42.com> @PRossbach

# Install dependencies
RUN apt-get update && apt-get install -y \
    openjdk-7-jdk \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Define working directory
WORKDIR /data

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-armhf

# Define default command
CMD ["bash"]
