FROM bee42/rpi-golang:1.7

ENV REPO=emilevauge/whoamI

ENV OUTPUT_PATH=/output

RUN apt-get update && apt-get install -y --no-install-recommends git make 

ENV CGO_ENABLED=0 

RUN go get -d github.com/${REPO} && cd $GOPATH/src/github.com/${REPO} && go build -a --installsuffix cgo --ldflags="-s" -o whoami

RUN mkdir -p $OUTPUT_PATH && cp  src/github.com/${REPO}/whoami $OUTPUT_PATH/


