FROM armhfbuild/golang:1.6-alpine

RUN export OUTPUT_PATH=/output \
    && apk add --no-cache git make bash gcc linux-headers python musl-dev  \
    && go get -d github.com/emilevauge/whoamI \
    && cd $GOPATH/src/github.com/emilevauge/whoamI \
    && CGO_ENABLED=0 go build -a --installsuffix cgo --ldflags="-s" -o whoamI \
    && cp whoamI ${OUTPUT_PATH} 
