FROM bee42/rpi-golang:1.7

ENV REPO=docker/distribution

ENV OUTPUT_PATH=/output

RUN apt-get update && apt-get install -y --no-install-recommends git make 

ENV CGO_ENABLED=0 

RUN go get -d github.com/${REPO} && cd $GOPATH/src/github.com/${REPO} && make clean binaries

RUN cp -R src/github.com/${REPO}/bin/ $OUTPUT_PATH/
